### ISSUE TITLE
Laravel webmix

### ISSUE THREAD

**Issue by hrace009** [Remix-Design/RemixIcon#388]
Helo,

I try to add this pack to my laravel project using `@import '~remixicon/fonts/remixicon.css';`
but i got this error:
```
ERROR in ./resources/css/app.css
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
Error: Failed to find '~remixicon/fonts/remixicon.css'
  in [
    C:\xampp\htdocs\Laravel\resources\css
  ]
    at C:\xampp\htdocs\Laravel\node_modules\postcss-import\lib\resolve-id.js:35:13
    at async LazyResult.runAsync (C:\xampp\htdocs\Laravel\node_modules\postcss\lib\lazy-result.js:396:11)
    at async Object.loader (C:\xampp\htdocs\Laravel\node_modules\postcss-loader\dist\index.js:97:14)
    at processResult (C:\xampp\htdocs\Laravel\node_modules\webpack\lib\NormalModule.js:753:19)
    at C:\xampp\htdocs\Laravel\node_modules\webpack\lib\NormalModule.js:855:5
    at C:\xampp\htdocs\Laravel\node_modules\loader-runner\lib\LoaderRunner.js:399:11
    at C:\xampp\htdocs\Laravel\node_modules\loader-runner\lib\LoaderRunner.js:251:18
    at context.callback (C:\xampp\htdocs\Laravel\node_modules\loader-runner\lib\LoaderRunner.js:124:13)
    at Object.loader (C:\xampp\htdocs\Laravel\node_modules\postcss-loader\dist\index.js:142:7)

1 ERROR in child compilations (Use 'stats.children: true' resp. '--stats-children' for more details)
webpack compiled with 2 errors
```
Any solution?

Thanks

**Comment by hrace009** [comment]
sorry my bad, it should place to app.js
